Document: flyback
Title: Debian Flyback Manual
Author: <insert document author here>
Abstract: This manual describes what Flyback is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/flyback/flyback.sgml.gz

Format: postscript
Files: /usr/share/doc/flyback/flyback.ps.gz

Format: text
Files: /usr/share/doc/flyback/flyback.text.gz

Format: HTML
Index: /usr/share/doc/flyback/html/index.html
Files: /usr/share/doc/flyback/html/*.html
